[package]
name = "logic_diagram_generator"
version = "0.1.0"
authors = ["Aaron <aaronmp01@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.13"
rusttype = "0.9.2"